name       : python-apscheduler
version    : 3.8.1
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/A/APScheduler/APScheduler-3.8.1.tar.gz : 5cf344ebcfbdaa48ae178c029c055cec7bc7a4a47c21e315e4d1f08bd35f2355
license    : MIT
component  : programming.python
summary    : Advanced Python Scheduler
description: |
    Advanced Python Scheduler (APScheduler) is a Python library that lets you schedule your Python code to be executed later, either just once or periodically.
builddeps  :
    - python-pytest-cov
    - python-setuptools-scm
    - python-tornado
    - python-tzlocal
rundeps    :
    - python-six
    - python-tzlocal
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    #python3_test py.test3 -v -k 'not test_executors_py35'
